<?php

// Data functions (insert, update, delete, form) for table personal_details

// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

function personal_details_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('personal_details');
	if(!$arrPerm[1]){
		return false;
	}

	$data['full_name'] = makeSafe($_REQUEST['full_name']);
		if($data['full_name'] == empty_lookup_value){ $data['full_name'] = ''; }
	$data['infection'] = makeSafe($_REQUEST['infection']);
		if($data['infection'] == empty_lookup_value){ $data['infection'] = ''; }
	$data['symptom'] = makeSafe($_REQUEST['symptom']);
		if($data['symptom'] == empty_lookup_value){ $data['symptom'] = ''; }
	$data['category'] = makeSafe($_REQUEST['category']);
		if($data['category'] == empty_lookup_value){ $data['category'] = ''; }

	// hook: personal_details_before_insert
	if(function_exists('personal_details_before_insert')){
		$args=array();
		if(!personal_details_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `personal_details` set       `full_name`=' . (($data['full_name'] !== '' && $data['full_name'] !== NULL) ? "'{$data['full_name']}'" : 'NULL') . ', `infection`=' . (($data['infection'] !== '' && $data['infection'] !== NULL) ? "'{$data['infection']}'" : 'NULL') . ', `symptom`=' . (($data['symptom'] !== '' && $data['symptom'] !== NULL) ? "'{$data['symptom']}'" : 'NULL') . ', `category`=' . (($data['category'] !== '' && $data['category'] !== NULL) ? "'{$data['category']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"personal_details_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: personal_details_after_insert
	if(function_exists('personal_details_after_insert')){
		$res = sql("select * from `personal_details` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!personal_details_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('personal_details', $recID, getLoggedMemberID());

	return $recID;
}

function personal_details_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('personal_details');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='personal_details' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='personal_details' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: personal_details_before_delete
	if(function_exists('personal_details_before_delete')){
		$args=array();
		if(!personal_details_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `personal_details` where `id`='$selected_id'", $eo);

	// hook: personal_details_after_delete
	if(function_exists('personal_details_after_delete')){
		$args=array();
		personal_details_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='personal_details' and pkValue='$selected_id'", $eo);
}

function personal_details_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('personal_details');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='personal_details' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='personal_details' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['full_name'] = makeSafe($_REQUEST['full_name']);
		if($data['full_name'] == empty_lookup_value){ $data['full_name'] = ''; }
	$data['infection'] = makeSafe($_REQUEST['infection']);
		if($data['infection'] == empty_lookup_value){ $data['infection'] = ''; }
	$data['symptom'] = makeSafe($_REQUEST['symptom']);
		if($data['symptom'] == empty_lookup_value){ $data['symptom'] = ''; }
	$data['category'] = makeSafe($_REQUEST['category']);
		if($data['category'] == empty_lookup_value){ $data['category'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: personal_details_before_update
	if(function_exists('personal_details_before_update')){
		$args=array();
		if(!personal_details_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `personal_details` set       `full_name`=' . (($data['full_name'] !== '' && $data['full_name'] !== NULL) ? "'{$data['full_name']}'" : 'NULL') . ', `infection`=' . (($data['infection'] !== '' && $data['infection'] !== NULL) ? "'{$data['infection']}'" : 'NULL') . ', `symptom`=' . (($data['symptom'] !== '' && $data['symptom'] !== NULL) ? "'{$data['symptom']}'" : 'NULL') . ', `category`=' . (($data['category'] !== '' && $data['category'] !== NULL) ? "'{$data['category']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="personal_details_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: personal_details_after_update
	if(function_exists('personal_details_after_update')){
		$res = sql("SELECT * FROM `personal_details` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!personal_details_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='personal_details' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function personal_details_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('personal_details');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_infection = thisOr(undo_magic_quotes($_REQUEST['filterer_infection']), '');
	$filterer_symptom = thisOr(undo_magic_quotes($_REQUEST['filterer_symptom']), '');

	// populate filterers, starting from children to grand-parents
	if($filterer_symptom && !$filterer_infection) $filterer_infection = sqlValue("select infection from symptoms where id='" . makeSafe($filterer_symptom) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: infection
	$combo_infection = new DataCombo;
	// combobox: symptom, filterable by: infection
	$combo_symptom = new DataCombo;
	// combobox: category
	$combo_category = new Combo;
	$combo_category->ListType = 0;
	$combo_category->MultipleSeparator = ', ';
	$combo_category->ListBoxHeight = 10;
	$combo_category->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/personal_details.category.csv')){
		$category_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/personal_details.category.csv')));
		$combo_category->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($category_data)));
		$combo_category->ListData = $combo_category->ListItem;
	}else{
		$combo_category->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("1;;2;;3;;4;;5;;6")));
		$combo_category->ListData = $combo_category->ListItem;
	}
	$combo_category->SelectName = 'category';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='personal_details' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='personal_details' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `personal_details` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'personal_details_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_infection->SelectedData = $row['infection'];
		$combo_symptom->SelectedData = $row['symptom'];
		$combo_category->SelectedData = $row['category'];
	}else{
		$combo_infection->SelectedData = $filterer_infection;
		$combo_symptom->SelectedData = $filterer_symptom;
		$combo_category->SelectedText = ( $_REQUEST['FilterField'][1]=='5' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
	}
	$combo_infection->HTML = '<span id="infection-container' . $rnd1 . '"></span><input type="hidden" name="infection" id="infection' . $rnd1 . '" value="' . html_attr($combo_infection->SelectedData) . '">';
	$combo_infection->MatchText = '<span id="infection-container-readonly' . $rnd1 . '"></span><input type="hidden" name="infection" id="infection' . $rnd1 . '" value="' . html_attr($combo_infection->SelectedData) . '">';
	$combo_symptom->HTML = '<span id="symptom-container' . $rnd1 . '"></span><input type="hidden" name="symptom" id="symptom' . $rnd1 . '" value="' . html_attr($combo_symptom->SelectedData) . '">';
	$combo_symptom->MatchText = '<span id="symptom-container-readonly' . $rnd1 . '"></span><input type="hidden" name="symptom" id="symptom' . $rnd1 . '" value="' . html_attr($combo_symptom->SelectedData) . '">';
	$combo_category->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_infection__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['infection'] : $filterer_infection); ?>"};
		AppGini.current_symptom__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['symptom'] : $filterer_symptom); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(infection_reload__RAND__) == 'function') infection_reload__RAND__();
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(symptom_reload__RAND__) == \'function\') symptom_reload__RAND__(AppGini.current_infection__RAND__.value);' : ''); ?>
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function infection_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#infection-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_infection__RAND__.value, t: 'personal_details', f: 'infection' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="infection"]').val(resp.results[0].id);
							$j('[id=infection-container-readonly__RAND__]').html('<span id="infection-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=infections_view_parent]').hide(); }else{ $j('.btn[id=infections_view_parent]').show(); }

						if(typeof(symptom_reload__RAND__) == 'function') symptom_reload__RAND__(AppGini.current_infection__RAND__.value);

							if(typeof(infection_update_autofills__RAND__) == 'function') infection_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'personal_details', f: 'infection' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_infection__RAND__.value = e.added.id;
				AppGini.current_infection__RAND__.text = e.added.text;
				$j('[name="infection"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=infections_view_parent]').hide(); }else{ $j('.btn[id=infections_view_parent]').show(); }

						if(typeof(symptom_reload__RAND__) == 'function') symptom_reload__RAND__(AppGini.current_infection__RAND__.value);

				if(typeof(infection_update_autofills__RAND__) == 'function') infection_update_autofills__RAND__();
			});

			if(!$j("#infection-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_infection__RAND__.value, t: 'personal_details', f: 'infection' },
					success: function(resp){
						$j('[name="infection"]').val(resp.results[0].id);
						$j('[id=infection-container-readonly__RAND__]').html('<span id="infection-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=infections_view_parent]').hide(); }else{ $j('.btn[id=infections_view_parent]').show(); }

						if(typeof(infection_update_autofills__RAND__) == 'function') infection_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_infection__RAND__.value, t: 'personal_details', f: 'infection' },
				success: function(resp){
					$j('[id=infection-container__RAND__], [id=infection-container-readonly__RAND__]').html('<span id="infection-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=infections_view_parent]').hide(); }else{ $j('.btn[id=infections_view_parent]').show(); }

					if(typeof(infection_update_autofills__RAND__) == 'function') infection_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function symptom_reload__RAND__(filterer_infection){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#symptom-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_infection: filterer_infection, id: AppGini.current_symptom__RAND__.value, t: 'personal_details', f: 'symptom' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="symptom"]').val(resp.results[0].id);
							$j('[id=symptom-container-readonly__RAND__]').html('<span id="symptom-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=symptoms_view_parent]').hide(); }else{ $j('.btn[id=symptoms_view_parent]').show(); }


							if(typeof(symptom_update_autofills__RAND__) == 'function') symptom_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { filterer_infection: filterer_infection, s: term, p: page, t: 'personal_details', f: 'symptom' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_symptom__RAND__.value = e.added.id;
				AppGini.current_symptom__RAND__.text = e.added.text;
				$j('[name="symptom"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=symptoms_view_parent]').hide(); }else{ $j('.btn[id=symptoms_view_parent]').show(); }


				if(typeof(symptom_update_autofills__RAND__) == 'function') symptom_update_autofills__RAND__();
			});

			if(!$j("#symptom-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_symptom__RAND__.value, t: 'personal_details', f: 'symptom' },
					success: function(resp){
						$j('[name="symptom"]').val(resp.results[0].id);
						$j('[id=symptom-container-readonly__RAND__]').html('<span id="symptom-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=symptoms_view_parent]').hide(); }else{ $j('.btn[id=symptoms_view_parent]').show(); }

						if(typeof(symptom_update_autofills__RAND__) == 'function') symptom_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_symptom__RAND__.value, t: 'personal_details', f: 'symptom' },
				success: function(resp){
					$j('[id=symptom-container__RAND__], [id=symptom-container-readonly__RAND__]').html('<span id="symptom-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=symptoms_view_parent]').hide(); }else{ $j('.btn[id=symptoms_view_parent]').show(); }

					if(typeof(symptom_update_autofills__RAND__) == 'function') symptom_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/personal_details_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/personal_details_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Personal detail details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return personal_details_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return personal_details_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return personal_details_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#full_name').replaceWith('<div class=\"form-control-static\" id=\"full_name\">' + (jQuery('#full_name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#infection').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#infection_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#symptom').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#symptom_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#category').replaceWith('<div class=\"form-control-static\" id=\"category\">' + (jQuery('#category').val() || '') + '</div>'); jQuery('#category-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(infection)%%>', $combo_infection->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(infection)%%>', $combo_infection->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(infection)%%>', urlencode($combo_infection->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(symptom)%%>', $combo_symptom->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(symptom)%%>', $combo_symptom->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(symptom)%%>', urlencode($combo_symptom->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(category)%%>', $combo_category->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(category)%%>', $combo_category->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'infection' => array('infections', 'Infection'), 'symptom' => array('symptoms', 'Symptom'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(full_name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(infection)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(symptom)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(category)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(full_name)%%>', safe_html($urow['full_name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(full_name)%%>', html_attr($row['full_name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(full_name)%%>', urlencode($urow['full_name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(infection)%%>', safe_html($urow['infection']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(infection)%%>', html_attr($row['infection']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(infection)%%>', urlencode($urow['infection']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(symptom)%%>', safe_html($urow['symptom']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(symptom)%%>', html_attr($row['symptom']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(symptom)%%>', urlencode($urow['symptom']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(category)%%>', safe_html($urow['category']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(category)%%>', html_attr($row['category']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(category)%%>', urlencode($urow['category']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(full_name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(full_name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(infection)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(infection)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(symptom)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(symptom)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(category)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(category)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('personal_details');
	if($selected_id){
		$jdata = get_joined_record('personal_details', $selected_id);
		if($jdata === false) $jdata = get_defaults('personal_details');
		$rdata = $row;
	}
	$templateCode .= loadView('personal_details-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: personal_details_dv
	if(function_exists('personal_details_dv')){
		$args=array();
		personal_details_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>