<?php
// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
    $ids='<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
	// mm: can the current member access this page?
	$perm=getTablePermissions('online');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		// echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}else{
        
        $headerCode='';
	if(function_exists('online_header')){
		$args=array();
		$headerCode=online_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}
        include("pharmacy_view.html");
    

    $footerCode='';
	if(function_exists('online_footer')){
		$args=array();
		$footerCode=online_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
    }
    
}
?>